routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['namespace' => 'Back'], function(){
    Route::get('login'               ,'LoginController@login')->name('login');
    Route::post('auth'               ,'LoginController@auth')->name('auth');

    Route::group(['middleware' => ['web','auth']], function () {
        Route::get('logout'          ,'LoginController@logout')->name('logout');
        Route::get('/'                   ,'HomeController@index'  )->name('app.home');
        Route::resource('users'          ,'UserController'        );
        Route::resource('warehouse_employees','WarehouseEmployee'  );
        Route::resource('categories'     ,'CategoryController'    );
        Route::resource('subcategories'  ,'SubCategoryController' );
        Route::resource('products'       ,'ProductController'     );
        Route::resource('providers'      ,'ProviderController'    );
        //Save
        Route::resource('save'           ,'SaveController'        );

        Route::resource('bills'          ,'BillController'        );
        Route::resource('supply_bills'   ,'SupplyBillController');

        Route::get('bills/print/{id}'                   ,'BillController@print')->name('bills.print');
        Route::get('bills/change/{id}/{type}'           ,'BillController@change')->name('bills.change');

        //Movement
        Route::get('product/move' ,'MoveController@productMove')->name('move.product');
        Route::get('user/move'    ,'MoveController@userMove')->name('move.user');
        Route::get('provider/moce','MoveController@providerMove')->name('move.provider');

        //Pay user
        Route::get('pay/users'             ,'PaymentController@userPay')->name('pay.users');
        Route::get('pay/users/create'      ,'PaymentController@userPayCreate' )->name('pay.users.create');
        Route::post('pay/users/store'      ,'PaymentController@userPayStore'  )->name('pay.users.store' );
        Route::get('pay/users/edit/{id}'   ,'PaymentController@userPayEdit'   )->name('pay.users.edit'  );
        Route::post('pay/users/update/{id}','PaymentController@userPayUpdate' )->name('pay.users.update');
        Route::get('pay/users/delete/{id}' ,'PaymentController@userPayDestroy')->name('pay.users.delete');

        //Pay Provider
        Route::get('pay/providers'             ,'PaymentController@providerPay'       )->name('pay.providers'        );
        Route::get('pay/providers/create'      ,'PaymentController@providerPayCreate' )->name('pay.providers.create' );
        Route::post('pay/providers/sotre'      ,'PaymentController@providerPayStore'  )->name('pay.providers.store'  );
        Route::get('pay/providers/edit/{id}'   ,'PaymentController@providerPayEdit'   )->name('pay.providers.edit'   );
        Route::post('pay/providers/update/{id}','PaymentController@providerPayUpdate' )->name('pay.providers.update' );
        Route::get('pay/providers/delete/{id}' ,'PaymentController@providerPayDestroy')->name('pay.providers.delete' );



        Route::get('user/bill'                ,'UserBillController@viewUserBill')->name('viewUsersBills');
        Route::get('create/users/bill'        ,'BillController@createUsersBills')->name('createUsersBills');
        Route::post('store/users/bill'        ,'BillController@storeUsersBills')->name('storeUsersBills');
        Route::get('get/bill/users'           ,'BillController@getBillUsers');
        Route::get('providers/bill'           ,'BillController@viewProviderBill')->name('viewProvidersBills');
        Route::get('create/providers/bill'    ,'BillController@createProvidersBills')->name('bills.createProvidersBills');
        Route::post('store/providers/bill'    ,'BillController@storeProvidersBills')->name('bills.storeProvidersBills');
        Route::get('fix/bill'                 ,'BillController@viewFixBill')->name('bills.viewFixBills');
        Route::get('create/fix/bill'          ,'BillController@createFixBill')->name('bills.createFixBills');
        Route::post('store/fix/bill'          ,'BillController@storeFixBill')->name('bills.storeFixBill');
        Route::resource('reports'             ,'ReportController'      );
        Route::get('product/get/product/price','ProductController@getPrice');
        Route::get('product/get/products'     ,'ProductController@getProducts');
        Route::get('user/get/total'           ,'PaymentController@total');
        //Short Fall
        Route::get('provider/shortfalls'            ,'ShortFallController@short')->name('provider.short');
        Route::get('provider/shortfalls/{id}'       ,'ShortFallController@providerShort')->name('provider.short.one');


        // ================== Ajax Route ======================
        Route::group(['prefix' => 'ajax'], function(){
            Route::get('get_subcategory/{main_category_id}', 'AjaxController@get_subcategory')->name('get_subcategory');
            Route::get('search_products', 'AjaxController@search_products')->name('search_products');
            Route::post('product/store', 'AjaxController@product_store')->name('products.store');
        });

        // ================== End Ajax Route ==================
    });


});

Route::group(['prefix' => 'warehouse' , 'namespace'=>'Warehouse','as'=>'warehouse.'], function () {
  Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'Auth\LoginController@login');
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

  //Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
  //Route::post('/register', 'Auth\RegisterController@register');

  Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
});

app/Http/Controllers/Back/SubCategoryController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Http\Requests\Back\SubCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class SubCategoryController extends Controller
{
    public function index()
    {
        $categories = Category::where('parent_id','!=',null)->get();
        return view('Front.subcategory.index',compact('categories'));
    }

    public function create()
    {
        $categories = Category::where('parent_id',null)->get()->pluck('name','id');

        return view('Front.subcategory.create',compact('categories'));
    }

    public function edit($id)
    {
        $subcategory = Category::findOrFail($id);
        $categories = Category::where('parent_id',null)->get()->pluck('name','id');
        return view('Front.subcategory.edit', compact('subcategory','categories'));
    }

    public function store(SubCategoryRequest $request)
    {
        Category::create($request->validated());
        return redirect(route('subcategories.index'))->withTrue('تم الإضافة بنجاح');
    }

    public function update(SubCategoryRequest $request, Category $subcategory)
    {
        $subcategory->update($request->validated());
        return redirect(route('subcategories.index'))->withTrue('تم الإضافة بنجاح');

    }

    public function destroy(Category $subcategory)
    {
        $subcategory->delete();
        return response()->json(['value' => 1]);

    }
}

resources/views/Front/subcategory/create.blade.php
@extends('Front.layouts.master')
@section('title', 'إضافة قسم جديدة')
@section('content')
<div class="row">
        <div class="col-12">
                <h1>رئيسية التحكم</h1>
                <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                    <ol class="breadcrumb pt-0">
                        <li class="breadcrumb-item"><a href="{{ url('/') }}">الرئيسية</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('subcategories.index') }}">الآقسام</a></li>
                        <li class="breadcrumb-item active" aria-current="page">إضافة قسم فرعي جديد</li>
                    </ol>
                </nav>
                <div class="separator mb-5"></div>
        </div>
        <div class="col-12">
                <div class="card mb-4">
                    <div class="card-body">
                    <form action="{{ route('subcategories.store') }}" method="POST">
                        @csrf
                        @include('Front.subcategory.form')
                    </form>
                    </div>
                 </div>
        </div>
</div>

@endsection

resources/views/Front/subcategory/edit.blade.php
@extends('Front.layouts.master')
@section('title', 'تعديل القسم')
@section('content')
    <div class="row">
        <div class="col-12">
            <h1>رئيسية التحكم</h1>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{{ url('/') }}">الرئيسية</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('subcategories.index') }}">الآقسام</a></li>
                    <li class="breadcrumb-item active" aria-current="page">تعديل قسم فرعي </li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-body">
            <form action="{{ route('subcategories.update', ['subcategory' => $subcategory]) }}" method="post">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                @include('Front.subcategory.form')
            </form>

            </div>
        </div>
        </div>
        </div>
@endsection

resources/views/Front/subcategory/form.blade.php
<div class="form-group">
    <label for="name">الإسم</label>
    <input name="name" type="text" @isset($subcategory) value="{{$subcategory->name}}" @else value="{{ old('name') }}" @endisset class="form-control @error('name') is-invalid @enderror">
    @error('name')
    <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>

<div class="form-group">
        <label for="desc">الوصف </label>
        <input type="text" name="desc" id="desc"  @isset($subcategory) value="{{$subcategory->desc}}" @else value="{{ old('desc') }}" @endisset class="form-control @error('desc') is-invalid @enderror">
        @error('desc')
        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
        @enderror
</div>

<div class="form-group">
    <label for="parent_id">القسم الرئيسي</label>

    <select class="form-control select2-single" name="parent_id" id="parent_id" >
        <option label="&nbsp;">&nbsp;</option>
        @foreach($categories as $key => $category)
            <option value="{{$key}}" @isset($subcategory)  @if($key == $subcategory->parent_id)  selected @endif @endisset>{{ $category }}</option>
        @endforeach
    </select>
</div>






<div class="form-group">
    <div class="col-xs-12">
        <button type="submit" name="submit" class="btn btn-primary">حفظ</button>
    </div>
</div>

resources/views/Front/subcategory/index.blade.php
@extends('Front.layouts.master')

@section('title', 'Sub-Category')
@section('styles')
<style>
    div.dataTables_filter {
        text-align: left;
        float: left;
    }
</style>
@endsection
@section('content')
    <div class="container-fluid disable-text-selection">
        <div class="row">
            <div class="col-12">
                <div class="mb-2">
                    <h1>آقسام الفرعيه للمنتجات</h1>
                    <div class="float-sm-right text-zero">
                        <a href="{{route('subcategories.create')}}"  class="btn btn-primary btn-lg mr-1">إضافة</a>

                    </div>
                    <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                        <ol class="breadcrumb pt-0">
                            <li class="breadcrumb-item">
                                <a href="#">الرئيسية</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">الآقسام الفرعية</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">البيانات</li>
                        </ol>
                    </nav>
                </div>

                <div class="mb-2">
                    <a class="btn pt-0 pl-0 d-inline-block d-md-none" data-toggle="collapse" href="#displayOptions"
                       role="button" aria-expanded="true" aria-controls="displayOptions">
                        Display Options
                        <i class="simple-icon-arrow-down align-middle"></i>
                    </a>
{{--                    <div class="collapse d-md-block" id="displayOptions">--}}
{{--                        <div class="d-block d-md-inline-block">--}}
{{--                            <div class="search-sm d-inline-block float-md-left mr-1 mb-1 align-top">--}}
{{--                                <input placeholder="Search...">--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
                </div>
                <div class="separator mb-5"></div>
            </div>
        </div>

        <div class="row">

                    <div class="col-12 list">
                        <div class="card h-100">
                            <div class="card-body">
                                <h5 class="card-title"> الآقسام الفرعية</h5>
                                <table id="example"  style="width:100%" class="dataTables table table-striped table-bordered cell-border compact stripe">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>الإسم</th>
                                        <th>الوصف</th>
                                        <th> القسم الرئيسي </th>
                                        <th> خيارات </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($categories as $subcategory)
                                        <tr class="{{ $subcategory->id }}">
                                            <td> {{ $loop->iteration }} </td>

                                            <td>
                                                <p class="list-item-heading"> {{ $subcategory->name  }}</p>
                                            </td>
                                            <td>
                                                <p class="text-muted">{{ $subcategory->desc }}</p>
                                            </td>
                                            <td>
                                                <p class="text-muted"> {{$subcategory->maincategory->name}} </p>
                                            </td>
                                            <td>
                                                <a href="{{ route('subcategories.edit',[$subcategory->id]) }}">
                                                    <span class="badge badge-pill badge-secondary">تعديل</span>
                                                </a>
                                                <a onclick="deleteItem({{ $subcategory->id }} , '{{ route('subcategories.destroy',$subcategory->id) }}')" >
                                                    <span class="badge badge-pill badge-danger">حذف</span>
                                                </a>
                                            </td>


                                        </tr>

                                    
                                    @endforeach


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>
  @include('Front.includes.delete_model')
@stop
@section('js')
<script>
    $(document).ready(function(){
        $('<div class="loading">Loading</div>').appendTo('body');

        $('#example').DataTable({
            "initComplete": function( settings, json ) {
                $('div.loading').remove();
              },
            language:{
                "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/Arabic.json"
            },
            keys: true,
            scrollX:true,
            autoheight:true,



        });
        $('div.dataTables_filter input').focus()

    });
</script>
@endsection