routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['namespace' => 'Back'], function(){
    Route::get('login'               ,'LoginController@login')->name('login');
    Route::post('auth'               ,'LoginController@auth')->name('auth');

    Route::group(['middleware' => ['web','auth']], function () {
        Route::get('logout'          ,'LoginController@logout')->name('logout');
        Route::get('/'                   ,'HomeController@index'  )->name('app.home');
        Route::resource('users'          ,'UserController'        );
        Route::resource('warehouse_employees','WarehouseEmployee'  );
        Route::resource('categories'     ,'CategoryController'    );
        Route::resource('subcategories'  ,'SubCategoryController' );
        Route::resource('products'       ,'ProductController'     );
        Route::resource('providers'      ,'ProviderController'    );
        //Save
        Route::resource('save'           ,'SaveController'        );

        Route::resource('bills'          ,'BillController'        );
        Route::resource('supply_bills'   ,'SupplyBillController');

        Route::get('bills/print/{id}'                   ,'BillController@print')->name('bills.print');
        Route::get('bills/change/{id}/{type}'           ,'BillController@change')->name('bills.change');

        //Movement
        Route::get('product/move' ,'MoveController@productMove')->name('move.product');
        Route::get('user/move'    ,'MoveController@userMove')->name('move.user');
        Route::get('provider/moce','MoveController@providerMove')->name('move.provider');

        //Pay user
        Route::get('pay/users'             ,'PaymentController@userPay')->name('pay.users');
        Route::get('pay/users/create'      ,'PaymentController@userPayCreate' )->name('pay.users.create');
        Route::post('pay/users/store'      ,'PaymentController@userPayStore'  )->name('pay.users.store' );
        Route::get('pay/users/edit/{id}'   ,'PaymentController@userPayEdit'   )->name('pay.users.edit'  );
        Route::post('pay/users/update/{id}','PaymentController@userPayUpdate' )->name('pay.users.update');
        Route::get('pay/users/delete/{id}' ,'PaymentController@userPayDestroy')->name('pay.users.delete');

        //Pay Provider
        Route::get('pay/providers'             ,'PaymentController@providerPay'       )->name('pay.providers'        );
        Route::get('pay/providers/create'      ,'PaymentController@providerPayCreate' )->name('pay.providers.create' );
        Route::post('pay/providers/sotre'      ,'PaymentController@providerPayStore'  )->name('pay.providers.store'  );
        Route::get('pay/providers/edit/{id}'   ,'PaymentController@providerPayEdit'   )->name('pay.providers.edit'   );
        Route::post('pay/providers/update/{id}','PaymentController@providerPayUpdate' )->name('pay.providers.update' );
        Route::get('pay/providers/delete/{id}' ,'PaymentController@providerPayDestroy')->name('pay.providers.delete' );



        Route::get('user/bill'                ,'UserBillController@viewUserBill')->name('viewUsersBills');
        Route::get('create/users/bill'        ,'BillController@createUsersBills')->name('createUsersBills');
        Route::post('store/users/bill'        ,'BillController@storeUsersBills')->name('storeUsersBills');
        Route::get('get/bill/users'           ,'BillController@getBillUsers');
        Route::get('providers/bill'           ,'BillController@viewProviderBill')->name('viewProvidersBills');
        Route::get('create/providers/bill'    ,'BillController@createProvidersBills')->name('bills.createProvidersBills');
        Route::post('store/providers/bill'    ,'BillController@storeProvidersBills')->name('bills.storeProvidersBills');
        Route::get('fix/bill'                 ,'BillController@viewFixBill')->name('bills.viewFixBills');
        Route::get('create/fix/bill'          ,'BillController@createFixBill')->name('bills.createFixBills');
        Route::post('store/fix/bill'          ,'BillController@storeFixBill')->name('bills.storeFixBill');
        Route::resource('reports'             ,'ReportController'      );
        Route::get('product/get/product/price','ProductController@getPrice');
        Route::get('product/get/products'     ,'ProductController@getProducts');
        Route::get('user/get/total'           ,'PaymentController@total');
        //Short Fall
        Route::get('provider/shortfalls'            ,'ShortFallController@short')->name('provider.short');
        Route::get('provider/shortfalls/{id}'       ,'ShortFallController@providerShort')->name('provider.short.one');


        // ================== Ajax Route ======================
        Route::group(['prefix' => 'ajax'], function(){
            Route::get('get_subcategory/{main_category_id}', 'AjaxController@get_subcategory')->name('get_subcategory');
            Route::get('search_products', 'AjaxController@search_products')->name('search_products');
            Route::post('product/store', 'AjaxController@product_store')->name('products.store');
        });

        // ================== End Ajax Route ==================
    });


});

Route::group(['prefix' => 'warehouse' , 'namespace'=>'Warehouse','as'=>'warehouse.'], function () {
  Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'Auth\LoginController@login');
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

  //Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
  //Route::post('/register', 'Auth\RegisterController@register');

  Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
});

app/Http/Controllers/Back/WarehouseEmployee.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Warehouse;
use App\Http\Requests\Back\WarehouseEmployeeRequest;

class WarehouseEmployee extends Controller
{
    protected $path;

    public function __construct()
    {
        $this->path = 'Front.warehouse_employees.';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Warehouse::all();
        return view($this->path.'index',compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->path.'create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(WarehouseEmployeeRequest $request)
    {

        $inputs = $request->validated();
        if($request->image){
            $inputs['image'] = uploaded($request->image,(new Warehouse)->getTable());
        }
        if($request->password){
            $inputs['password']=bcrypt($request->password);
        }
        $employee = Warehouse::create($inputs);

        return redirect(route('warehouse_employees.index'))->withTrue('تم تسجيل الموظف بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Warehouse::findOrFail($id);
        return view($this->path.'edit',compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(WarehouseEmployeeRequest $request, $id)
    {
        $employee = Warehouse::findOrFail($id);

      $inputs = $request->validated();
      if($request->image){
          $inputs['image'] = uploaded($request->image,(new Warehouse)->getTable());
      }
      if($request->password){
          $inputs['password']=bcrypt($request->password);
      }else {
        unset($inputs['password']);
      }
      $employee->update($inputs);

      return redirect(route('warehouse_employees.index'))->withTrue('تم تعديل البيانات بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $user = Warehouse::findOrFail($id);
      $user->delete();
      return response()->json(['value' => 1]);
    }
}

resources/views/Front/warehouse_employees/create.blade.php
@extends('Front.layouts.master')

@section('title', 'اضافة عميل جديد')

@section('content')
    <div class="row">
        <div class="col-12">
            <h1>رئيسية التحكم</h1>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{{ url('/') }}">الرئيسية</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('warehouse_employees.index') }}">موظفين المخازن</a></li>
                    <li class="breadcrumb-item active" aria-current="page">إضافة موظف  جديد</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-body">
                <form action="{{ route('warehouse_employees.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @include('Front.warehouse_employees.form')
                </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/Front/warehouse_employees/edit.blade.php
@extends('Front.layouts.master')

@section('title', 'تعديل عميل')

@section('content')
    <div class="row">
        <div class="col-12">
            <h1>رئيسية التحكم</h1>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{{ url('/') }}">الرئيسية</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('warehouse_employees.index') }}">موظفين المخازن</a></li>
                    <li class="breadcrumb-item active" aria-current="page">موظف عضو</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
        <div class="col-12">
            <div class="card mb-4">
            <div class="card-body">
            <form action="{{ route('warehouse_employees.update',$employee->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                @include('Front.warehouse_employees.form')
            </form>
            </div>
            </div>
        </div>
    </div>
@stop

resources/views/Front/warehouse_employees/form.blade.php
<div class="row">
  <div class="from-group col-md-12">
    <label for="name">نوع الموظف</label>
    <select class="form-control select2-single " name="type" id="type" >
        <option value="manger" @isset($employee)  @if($employee->type == 'manger')  selected @endif @endisset >لديه صلاحية الدخول علي النظام</option>
        <option value="employee" @isset($employee)  @if($employee->type == 'employee')  selected @endif @endisset >موظف مراجعة و ليس له دخول علي النظام</option>
    </select>
  </div>
<div class="form-group col-md-6">
    <label for="name">الإسم</label>
    <input name="name" type="text" @isset($employee) value="{{$employee->name}}" @else value="{{ old('name') }}" @endisset class="form-control @error('name') is-invalid @enderror">
    @error('name')
    <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>
<div class="form-group col-md-6">
    <label for="email"> البريد الالكتروني</label>
    <input type="email" name="email" id="email"  @isset($employee) value="{{$employee->email}}" @else value="{{ old('email') }}" @endisset class="form-control">
    @error('email')
    <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>

<div class="form-group col-md-6">
    <label for="password"> كلمة المرور</label>
    <input type="password" name="password" id="password"  class="form-control">
    @error('password')
    <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>


<div class="form-group col-md-6">
    <label for="password_confirmation">تأكيد كلمة المرور</label>
    <input type="password" name="password_confirmation" id="password_confirmation"  class="form-control">
    @error('password_confirmation')
    <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>
<div class="form-group col-md-6">
    <label for="phone"> الموبيل</label>
    <input type="phone" name="phone" id="phone"  @isset($employee) value="{{$employee->phone}}" @else value="{{ old('phone') }}" @endisset class="form-control">
    @error('phone')
    <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
    @enderror
</div>


<div class="form-group col-md-6">
        <label for="address">العنوان </label>
        <input type="text" name="address" id="address"  @isset($employee) value="{{$employee->address}}" @else value="{{ old('address') }}" @endisset class="form-control @error('address') is-invalid @enderror">
        @error('address')
        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
        @enderror
 </div>



<div class="form-group col-md-12">
  @isset($employee)

  <img src="{{ $employee->ImageUrl }}" width="80" height="80" style="margin: 7px;">

  @endisset
<div class="input-group   mb-3">
    <div class="input-group-prepend">
        <span class="input-group-text">
            الصورة
        </span>
    </div>
    <div class="custom-file">
        <input type="file" name="image" class="custom-file-input" id="inputGroupFile01">
         <label class="custom-file-label" for="inputGroupFile01">
            اختر الصورة
            </label>
        </div>
    </div>
</div>
</div>
<div class="form-group">
    <div class="col-xs-12">
        <button type="submit" name="submit" class="btn btn-primary">حفظ</button>
    </div>
</div>

resources/views/Front/warehouse_employees/index.blade.php
@extends('Front.layouts.master')

@section('title', 'موظفين المخازن')
@section('styles')
<style>
    div.dataTables_filter {
        text-align: left;
        float: left;
    }
</style>
@endsection
@section('content')
    <div class="container-fluid disable-text-selection">
        <div class="row">
            <div class="col-12">
                <div class="mb-2">
                    <h1>قائمة موظفين المخازن</h1>
                    <div class="float-sm-right text-zero">
                        <a href="{{route('warehouse_employees.create')}}"  class="btn btn-primary btn-lg mr-1">إضافة</a>
                    </div>
                    <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                        <ol class="breadcrumb pt-0">
                            <li class="breadcrumb-item">
                                <a href="#">الرئيسية</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">موظفين المخازن</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">عرض الكل</li>
                        </ol>
                    </nav>
                </div>

                <div class="mb-2">
                    <a class="btn pt-0 pl-0 d-inline-block d-md-none" data-toggle="collapse" href="#displayOptions"
                       role="button" aria-expanded="true" aria-controls="displayOptions">
                        Display Options
                        <i class="simple-icon-arrow-down align-middle"></i>
                    </a>
{{--                    <div class="collapse d-md-block" id="displayOptions">--}}
{{--                        <div class="d-block d-md-inline-block">--}}
{{--                            <div class="search-sm d-inline-block float-md-left mr-1 mb-1 align-top">--}}
{{--                                <input placeholder="Search...">--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
                </div>
                <div class="separator mb-5"></div>
            </div>
        </div>

        <div class="row">

                    <div class="col-12 list">
                        <div class="card h-100">
                            <div class="card-body">
                                <h5 class="card-title"> موظفين المخازن</h5>
                                <table id="example"  style="width:100%" class="dataTables table table-striped table-bordered cell-border compact stripe">
                                    <thead>
                                    <tr>
                                        <th class="text-center">#</th>
                                        <th class="text-center">الصورة</th>
                                        <th class="text-center">الإسم</th>
                                        <th class="text-center">البريد الالكتروني</th>
                                        <th class="text-center">الموبيل</th>
                                        <th class="text-center">العنوان</th>
                                        <th class="text-center">صلاحية الدخول للنظام</th>

                                        <th class="text-center"> خيارات </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($employees as $user)
                                        <tr class="{{ $user->id }}">
                                            <td class="text-center"> {{ $user->id }} </td>
                                            <td class="text-center"> <img src="{{ $user->ImageUrl }}" width="60" height="60"> </td>
                                            <td class="text-center">
                                                <p class="list-item-heading"> {{ $user->name  }}</p>
                                            </td>
                                            <td class="text-center">
                                                <p class="text-muted">{{ $user->email }}</p>
                                            </td>
                                            <td class="text-center">
                                                <p class="text-muted">{{ $user->phone }}</p>
                                            </td>
                                            <td class="text-center">
                                                <p class="text-muted"> {{$user->address}} </p>
                                            </td>
                                            <td class="text-center">
                                                <p class="text-muted"> {{ $user->type == 'manger'?'نعم':'لا - موظف مراجعة'}} </p>
                                            </td>


                                            <td class="text-center">
                                                <a href="{{ route('warehouse_employees.edit',[$user->id]) }}">
                                                    <span class="badge badge-pill badge-secondary btn btn-lg">تعديل</span>
                                                </a>
                                                <a onclick="deleteItem({{ $user->id }} , '{{ route('warehouse_employees.destroy',$user->id) }}')" >
                                                    <span class="badge badge-pill badge-danger btn btn-lg">حذف</span>
                                                </a>
                                            </td>


                                        </tr>


                                    @endforeach


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>
  @include('Front.includes.delete_model')
@stop
@section('js')
<script>
    $(document).ready(function(){
        $('<div class="loading">Loading</div>').appendTo('body');

        $('#example').DataTable({
            "initComplete": function( settings, json ) {
                $('div.loading').remove();
              },
            language:{
                "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/Arabic.json"
            },
            keys: true,
            scrollX:true,
            autoheight:true,



        });
        $('div.dataTables_filter input').focus()

    });
</script>
@endsection

resources/views/Front/warehouse_employees/move.blade.php
@extends('Front.layouts.master')

@section('title', 'Users')
@section('styles')
<style>
    div.dataTables_filter {
        text-align: left;
        float: left;
    }
</style>
@endsection
@section('content')
    <div class="container-fluid disable-text-selection">
        <div class="row">
            <div class="col-12">
                <div class="mb-2">
                    <h1>قائمة حركات العملاء</h1>
                    <div class="float-sm-right text-zero">
                    </div>
                    <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                        <ol class="breadcrumb pt-0">
                            <li class="breadcrumb-item">
                                <a href="#">الرئيسية</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#"> حركات العملاء </a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">البيانات</li>
                        </ol>
                    </nav>
                </div>

                <div class="mb-2">
                    <a class="btn pt-0 pl-0 d-inline-block d-md-none" data-toggle="collapse" href="#displayOptions"
                       role="button" aria-expanded="true" aria-controls="displayOptions">
                        Display Options
                        <i class="simple-icon-arrow-down align-middle"></i>
                    </a>

                </div>
                <div class="separator mb-5"></div>
            </div>
        </div>

        <div class="row">

                    <div class="col-12 list">
                        <div class="card h-100">
                            <div class="card-body">
                                <h5 class="card-title"> حركات العملاء</h5>
                                <table id="example"  style="width:100%" class="dataTables table table-striped table-bordered cell-border compact stripe">
                                    <thead>
                                    <tr>
                                        <th>رقم العميل</th>
                                        <th>الإسم</th>
                                        <th>الموبيل</th>
                                        <th>العنوان</th>
                                        <th> عدد الفواتير </th>
                                        <th> قيمة المديونية </th>
                                        <th> تاريخ آخر تحديث للعميل </th>
                                        <th>  آخر تاريخ فاتورة العميل    </th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse($users as $user)
                                        <tr class="{{ $user->id }}">
                                            <td> {{ $user->id }} </td>
                                            <td>
                                                <p class="list-item-heading"> {{ $user->name  }}</p>
                                            </td>
                                            <td>
                                                <p class="text-muted">{{ $user->phone }}</p>
                                            </td>
                                            <td>
                                                <p class="text-muted"> {{$user->address}} </p>
                                            </td>
                                            <td>
                                                <p class="text-muted">{{$user->bills->count()}}</p>
                                            </td>
                                            <td>
                                                <p class="text-muted">{{$user->total_money}}</p>
                                            </td>

                                            <td>
                                                <p class="text-muted">{{$user->last_date}}</p>
                                            </td>

                                            <td>
                                                <p class="text-muted"> {{ date('Y-m-d', strtotime(  $user->bills->last()->date)) }} </p>
                                            </td>
                                        </tr>

                                    @empty
                                        <tr>
                                            <td colspan="8"> لايوجد عملاء مضافين حتي الآن </td>
                                        </tr>
                                    @endforelse


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>
  @include('Front.includes.delete_model')
@stop
@section('js')
<script>
    $(document).ready(function(){
        $('<div class="loading">Loading</div>').appendTo('body');

        $('#example').DataTable({
            "initComplete": function( settings, json ) {
                $('div.loading').remove();
              },
            language:{
                "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/Arabic.json"
            },
            keys: true,
            scrollX:true,
            autoheight:true,



        });
        $('div.dataTables_filter input').focus()

    });
</script>
@endsection