routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['namespace' => 'Back'], function(){
    Route::get('login'               ,'LoginController@login')->name('login');
    Route::post('auth'               ,'LoginController@auth')->name('auth');

    Route::group(['middleware' => ['web','auth']], function () {
        Route::get('logout'          ,'LoginController@logout')->name('logout');
        Route::get('/'                   ,'HomeController@index'  )->name('app.home');
        Route::resource('users'          ,'UserController'        );
        Route::resource('warehouse_employees','WarehouseEmployee'  );
        Route::resource('categories'     ,'CategoryController'    );
        Route::resource('subcategories'  ,'SubCategoryController' );
        Route::resource('products'       ,'ProductController'     );
        Route::resource('providers'      ,'ProviderController'    );
        //Save
        Route::resource('save'           ,'SaveController'        );

        Route::resource('bills'          ,'BillController'        );
        Route::resource('supply_bills'   ,'SupplyBillController');

        Route::get('bills/print/{id}'                   ,'BillController@print')->name('bills.print');
        Route::get('bills/change/{id}/{type}'           ,'BillController@change')->name('bills.change');

        //Movement
        Route::get('product/move' ,'MoveController@productMove')->name('move.product');
        Route::get('user/move'    ,'MoveController@userMove')->name('move.user');
        Route::get('provider/moce','MoveController@providerMove')->name('move.provider');

        //Pay user
        Route::get('pay/users'             ,'PaymentController@userPay')->name('pay.users');
        Route::get('pay/users/create'      ,'PaymentController@userPayCreate' )->name('pay.users.create');
        Route::post('pay/users/store'      ,'PaymentController@userPayStore'  )->name('pay.users.store' );
        Route::get('pay/users/edit/{id}'   ,'PaymentController@userPayEdit'   )->name('pay.users.edit'  );
        Route::post('pay/users/update/{id}','PaymentController@userPayUpdate' )->name('pay.users.update');
        Route::get('pay/users/delete/{id}' ,'PaymentController@userPayDestroy')->name('pay.users.delete');

        //Pay Provider
        Route::get('pay/providers'             ,'PaymentController@providerPay'       )->name('pay.providers'        );
        Route::get('pay/providers/create'      ,'PaymentController@providerPayCreate' )->name('pay.providers.create' );
        Route::post('pay/providers/sotre'      ,'PaymentController@providerPayStore'  )->name('pay.providers.store'  );
        Route::get('pay/providers/edit/{id}'   ,'PaymentController@providerPayEdit'   )->name('pay.providers.edit'   );
        Route::post('pay/providers/update/{id}','PaymentController@providerPayUpdate' )->name('pay.providers.update' );
        Route::get('pay/providers/delete/{id}' ,'PaymentController@providerPayDestroy')->name('pay.providers.delete' );



        Route::get('user/bill'                ,'UserBillController@viewUserBill')->name('viewUsersBills');
        Route::get('create/users/bill'        ,'BillController@createUsersBills')->name('createUsersBills');
        Route::post('store/users/bill'        ,'BillController@storeUsersBills')->name('storeUsersBills');
        Route::get('get/bill/users'           ,'BillController@getBillUsers');
        Route::get('providers/bill'           ,'BillController@viewProviderBill')->name('viewProvidersBills');
        Route::get('create/providers/bill'    ,'BillController@createProvidersBills')->name('bills.createProvidersBills');
        Route::post('store/providers/bill'    ,'BillController@storeProvidersBills')->name('bills.storeProvidersBills');
        Route::get('fix/bill'                 ,'BillController@viewFixBill')->name('bills.viewFixBills');
        Route::get('create/fix/bill'          ,'BillController@createFixBill')->name('bills.createFixBills');
        Route::post('store/fix/bill'          ,'BillController@storeFixBill')->name('bills.storeFixBill');
        Route::resource('reports'             ,'ReportController'      );
        Route::get('product/get/product/price','ProductController@getPrice');
        Route::get('product/get/products'     ,'ProductController@getProducts');
        Route::get('user/get/total'           ,'PaymentController@total');
        //Short Fall
        Route::get('provider/shortfalls'            ,'ShortFallController@short')->name('provider.short');
        Route::get('provider/shortfalls/{id}'       ,'ShortFallController@providerShort')->name('provider.short.one');


        // ================== Ajax Route ======================
        Route::group(['prefix' => 'ajax'], function(){
            Route::get('get_subcategory/{main_category_id}', 'AjaxController@get_subcategory')->name('get_subcategory');
            Route::get('search_products', 'AjaxController@search_products')->name('search_products');
            Route::post('product/store', 'AjaxController@product_store')->name('products.store');
        });

        // ================== End Ajax Route ==================
    });


});

Route::group(['prefix' => 'warehouse' , 'namespace'=>'Warehouse','as'=>'warehouse.'], function () {
  Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'Auth\LoginController@login');
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

  //Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
  //Route::post('/register', 'Auth\RegisterController@register');

  Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
});

app/Models/Bill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Bill extends Model
{
    protected $guarded = ['id'];

    protected $dates = ['date'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id')->withDefault();
    }

    public function items()
    {
      return $this->hasMany(BillProduct::class,'bill_id');
    }

    public function Products()
    {
        return $this->belongsToMany(Product::class, 'bill_products', 'bill_id', 'product_id')->withPivot('q_price','quantity');
    }

    public function order()
    {
        return $this->hasOne(Order::class, 'bill_id', 'id');
    }


    public function payments()
    {
        return $this->hasMany(Payment::class, 'bill_id', 'id');
    }

    public function bill()
    {
        return $this->belongsTo(Bill::class, 'bill_id');
    }

}

app/Http/Controllers/Back/BillController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Http\Requests\Back\SellBillRequest;
use Illuminate\Http\Request;
use App\Models\Bill;
use App\Models\BillProduct;
use App\Models\Order;
use App\Models\Product;
use App\Models\User;
use Carbon\Carbon;
use Exception;

class BillController extends Controller
{
    public function index($type)
    {
      switch ($type) {
        case 'supply':
          // code...
          break;
      }
        $bills = Bill::get();
        return view('Front.bills.index', compact('bills'));
    }

    public function create(Request $request)
    {
      switch ($request->type) {
        case 'supply':
          $users = User::where('type','provider')->get()->pluck('name','id');
          break;
      }
        // $products = Product::where('amount','!=','0')->get()->pluck('name','id');

        return view('Front.bills.create',compact('users'));
    }

    public function store(SellBillRequest $request)
    {
            $inputs = array_except($request->validated(), ['product','amount','price']);
            $inputs['date'] = Carbon::now()->format('Y-m-d');
            for ($i=0; $i < count($request->product); $i++) {
                $orignalProduct = Product::find($request->product[$i]);
                if($orignalProduct->amount < 1  || $orignalProduct->max_amount < $request->amount[$i]){
                    return redirect()->route('bills.create')->withFalse('لايمكن إتمام الفاتورة بهذه الكمية من منتج '.$orignalProduct->name);
                }
            }

            $bill =  Bill::create($inputs);
            for ($i=0; $i < count($request->product); $i++) {
             $product =    new BillProduct ();
             $product->bill_id    = $bill->id;
             $product->product_id = $request->product[$i];
             $product->quantity   = $request->amount[$i];
             $product->price      = $request->price[$i] / $request->amount[$i];
             $product->q_price    = $request->price[$i];
             if($request->avilable){
                $product->avilable = $request->avilable;
             }else{
               $orignalProduct = Product::find($request->product[$i]);
               if($orignalProduct->amount < 1 ){
                $product->avilable = 0;
               }
             }
             if($request->bill_price){
                $product->bill_price = $request->bill_price[$i];
             }

             $product->save();
            }
            return redirect()->route('bills.index')->withTrue('تم إضافة الفاتورة بنجاح');

    }


    public function edit($id)
    {
        $bill = Bill::findOrFail($id);
        $products = Product::where('amount','!=','0')->get()->pluck('name','id');
        $users = User::get()->pluck('name','id');

        return view('Front.bills.edit', compact('bill','products','users'));
    }


    public function update(SellBillRequest $request,Bill  $bill)
    {
        if($bill->products){
            $bill->products()->detach();
        }


        $inputs = array_except($request->validated(), ['product','amount','price']);


        for ($i=0; $i < count($request->product); $i++) {
            $orignalProduct = Product::find($request->product[$i]);
            if($orignalProduct->amount < 1  || $orignalProduct->max_amount < $request->amount[$i]){
                return redirect()->route('bills.edit',[$bill->id])->withFalse('لايمكن إتمام الفاتورة بهذه الكمية من منتج '.$orignalProduct->name);
            }
        }

        $bill->update($inputs);
        for ($i=0; $i < count($request->product); $i++) {
         $product =    new BillProduct ();
         $product->bill_id    = $bill->id;
         $product->product_id = $request->product[$i];
         $product->quantity   = $request->amount[$i];
         $product->price      = $request->price[$i] / $request->amount[$i];
         $product->q_price    = $request->price[$i];
         if($request->avilable){
            $product->avilable = $request->avilable;
         }else{
           $orignalProduct = Product::find($request->product[$i]);
           if($orignalProduct->amount < 1 ){
            $product->avilable = 0;
           }
         }
         if($request->bill_price){
            $product->bill_price = $request->bill_price[$i];
         }

         $product->save();
        }
        return redirect()->route('bills.index')->withTrue('تم تعديل الفاتورة بنجاح');


    }

    public function destroy(Bill $bill)
    {

        $bill->products()->detach();
        $bill->delete();
        return response()->json(['value' => 1]);
    }

    public function getBillUsers(Request $request)
    {
        if($request->type == 'buy' ){
            $users = User::where('type','provider')->get()->pluck('name','id');
        }else{
            $users = User::where('type','user')->get()->pluck('name','id');
        }
        return  response()->json(['success','users'=>$users]);

    }

    public function print($id)
    {
        $bill = Bill::find($id);
        return view('Front.bills.print',compact('bill'));
    }

    public function change($id,$type)
    {
        $bill = Bill::find($id);
        if($type == 'bill'){
           $bill->status = 'bill';
        }elseif($type=='order'){
            $bill->status = 'order';
            foreach($bill->products as $product){
                $newProduct = Product::find($product->id);
                $newProduct->amount  -= $product->pivot->quantity;
                $newProduct->save();
            }
            $user = User::find($bill->user_id);
            if($user->total_money ==''||$user->total_money == null ||$user->total_money ==' '){
                $user->total_money  = $bill->total;
            }else{
                $user->total_money  += $bill->total;
            }
            $user->last_date = Carbon::now()->format('Y-m-d');
            $user->save();
            $order = new Order();
            $order->bill_id = $bill->id;
            $order->rest    = $bill->total;
            $order->save();
        }
        $bill->save();
       return  redirect()->route('bills.index')->withTrue('تم تعديل الفاتورة بنجاح');
    }



}

app/Http/Controllers/Back/SupplyBillController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Bill;
use App\Http\Requests\Back\SupplyBillRequest;

class SupplyBillController extends Controller
{
    protected $path;

    public function __construct()
    {
        $this->path = 'Front.bills.supply_bill.';
    }
   public function index()
    {
      $bills = Bill::whereType('supply_bill')->latest()->get();
      return view($this->path.'index',compact('bills'));
    }
    public function create()
    {
        $users = User::where('type', 'provider')->get()->pluck('name', 'id');
        $categories = Category::where('parent_id', null)->get()->pluck('name', 'id');
        $providers = User::where('type', 'provider')->get()->pluck('name', 'id');
        $subcategories = Category::where('parent_id', null)->get()->pluck('name', 'id');
        $latest_bill = Bill::latest()->first();
        if (!is_null($latest_bill)) {
            $code = $latest_bill->id + 1;
        } else {
            $code = 1;
        }
        return view($this->path . 'create', compact('users', 'code', 'categories', 'providers', 'subcategories'));
    }
    public function store(SupplyBillRequest $request)
    {
        \DB::beginTransaction();
          try {
            $inputs = array_except($request->validated(), ['products','discount']);
            $inputs['createor_id'] = auth()->id();
            $inputs['type'] = 'supply_bill';
            $inputs['status'] = 'pending';
            $bill =  Bill::create($inputs);

            $bill->items()->createMany($request->products);
            \DB::commit();
            } catch (\Exception $e) {
              \DB::rollback();
              return back()->withFalse('حدث خطأ أثناء التسجيل الرجاء المحاولة مرة أخري');
            }
            return redirect()->route('supply_bills.index')->withTrue('تم إضافة الفاتورة بنجاح');

    }
}

app/Http/Controllers/Warehouse/SupplyBillController.php
<?php

namespace App\Http\Controllers\Warehouse;

use App\Http\Controllers\Controller;
use App\Models\Bill;
use Illuminate\Http\Request;

class SupplyBillController extends Controller
{
    protected $path;

    public function __construct()
    {
        $this->path = 'warehouse.supply_bills.';
    }
    public function index(){
        $bills = Bill::whereType('supply_bill')->latest()->get();
        return view($this->path.'index',compact('bills'));
    }
}

resources/views/Front/bills/supply_bill/index.blade.php
@extends('Front.layouts.master')

@section('title', 'فواتير التوريد')
@section('styles')
    <style>
        div.dataTables_filter {
            text-align: left;
            float: left;
        }
    </style>
@endsection
@section('content')
    <div class="container-fluid disable-text-selection">
        <div class="row">
            <div class="col-12">
                <div class="mb-2">
                    <h1>فواتير التوريد</h1>
                    <div class="float-sm-right text-zero">
                        <a href="{{route('supply_bills.create')}}"  class="btn btn-primary btn-lg mr-1">إضافة أمر توريد جديد</a>

                    </div>
                    <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                        <ol class="breadcrumb pt-0">
                            <li class="breadcrumb-item">
                                <a href="#">الرئيسية</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">فواتير التوريد</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">عرض كل الفواتير</li>
                        </ol>
                    </nav>
                </div>
                </div>
                <div class="separator mb-5"></div>
            </div>
        </div>

        <div class="row">

            <div class="col-12 list">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title"> الفواتير</h5>

                        <table id="example"  style="width:100%" class="dataTables table table-striped table-bordered cell-border compact stripe">
                            <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">كود الفاتورة</th>
                                <th class="text-center">حالة الفاتورة</th>
                                <th class="text-center"> تاريخ صلاحية الفاتورة </th>
                                <th class="text-center"> عدد المنتجات </th>
                                <th class="text-center"> المورد </th>
                                <th class="text-center"> خيارات </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($bills as $bill)
                                <tr class="{{ $bill->id }}">
                                    <td class="text-center"> {{ $loop->iteration }} </td>
                                    <td class="text-center">{{ $bill->id }} </td>
                                    <td class="text-center">
                                        <p class="list-item-heading">
                                            @if($bill->status=='pending')
                                                <span class="badge badge-pill badge-warning"> لم يتم استلامها من ادارة المخازن</span>
                                            @else
                                                <span class="badge badge-pill badge-success"> تم استلامها من ادارة المخازن</span>
                                            @endif
                                        </p>
                                    </td>
                                    <td class="text-center">
                                        <p class="list-item-heading">
                                        @if(date('Y-m-d', strtotime( $bill->date)) >= now()->format('Y-m-d'))
                                            <span class="badge badge-pill badge-success">{{ date('Y-m-d', strtotime( $bill->date)) }}</span>
                                        @else
                                            <span class="badge badge-pill badge-danger">{{ date('Y-m-d', strtotime( $bill->date)) }}</span>
                                        @endif
                                        </p>
                                    </td>
                                    <td class="text-center">
                                        <p class="text-muted"> {{$bill->products->count()}} </p>
                                    </td>
                                    <td class="text-center">
                                        <p class="text-muted"> {{$bill->user->name}} </p>
                                    </td>

                                    <td class="text-center">
                                        <a href="{{ route('supply_bills.show',[$bill->id]) }}">
                                            <span class="badge badge-pill badge-warning">عرض</span>
                                        </a>
                                        <a href="{{ route('supply_bills.edit',[$bill->id]) }}">
                                            <span class="badge badge-pill badge-secondary">تعديل</span>
                                        </a>

                                        <a onclick="deleteItem({{ $bill->id }} , '{{ route('supply_bills.destroy',$bill->id) }}')" >
                                            <span class="badge badge-pill badge-danger">حذف</span>
                                        </a>
                                    </td>


                                </tr>


                            @endforeach


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    @include('Front.includes.delete_model')
@stop
@section('js')
    <script>
        $(document).ready(function(){
            $('#example').DataTable({
                language:{
                    "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/Arabic.json"
                },
                keys: true,
                scrollX:true,
                autoheight:true,
            });
        });
    </script>
@endsection